Date made dynamic
theZalmanian/Winter2023-CPW219-E-CommerceSite pull request #36
Opened 2023-02-22 11:27 UTC by predatorprasad

**Date has been made dynamic**
Fixes: #2

2023-02-22 22:44 UTC, theZalmanian requested changes
Please use the modern syntax: `` @DateTime.Now.Year `` instead of `` <%= DateTime.Now.Year %> ``

2023-02-23 05:46 UTC, predatorprasad commented
I have made necessary changes, & that should be it

2023-02-24 02:00 UTC, theZalmanian approved these changes

2023-02-24 02:02 UTC, merged

2023-02-24 02:02 UTC, theZalmanian commented
> I have made necessary changes, & that should be it

Thank you very much!